services:
  gophkeeper:
    build:
      dockerfile: Dockerfile
      context: .
    image: gophkeeper
    environment:
      - DATABASE_DSN=postgres://gophkeeper:P@ssw0rd@gophkeeper-db:5432/gophkeeper?sslmode=disable
      - GIN_MODE=release
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - gophkeeper
    depends_on:
      gophkeeper-db:
        condition: service_healthy
    stop_grace_period: 5s

  gophkeeper-db:
    image: postgres:15.3
    volumes:
      - type: bind
        source: db/data/
        target: /var/lib/postgresql/data
      - type: bind
        source: db/init/
        target: /docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    networks:
      - gophkeeper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d gophkeeper -U gophkeeper"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  gophkeeper:
